#!/bin/bash

# Original image (512x512)
input_image="favicon.png"

# Output sizes and filenames
sizes=("16x16" "32x32" "48x48" "64x64" "128x128" "256x256")

# Loop through sizes and create icons
for size in "${sizes[@]}"; do
  output_image="${size}.png"
  magick "$input_image" -resize "$size" "$output_image"
done

icotool -c ${sizes[@]/%/.png} -o favicon.ico
icotool -l favicon.ico
